# The subcommands generate, verify, and rewrite have flags. They can be
# specified on the command line or in a configuration file, as below.

# To learn more about each flag, run `docker lock generate --help`
generate:
  base-dir: .
  composefile-globs:
    - '**/*docker-compose.yml'
  composefile-recursive: true
  composefiles:
    - docker-compose.yml
  dockerfile-globs:
    - '**/Dockerfile'
  dockerfile-recursive: false
  dockerfiles:
    - Dockerfile
  kubernetesfile-globs:
    - '**/pod.yml'
  kubernetesfile-recursive: false
  kubernetesfiles:
    - deployment.yml
  env-file: .env
  exclude-all-composefiles: false
  exclude-all-dockerfiles: true
  exclude-all-kubernetesfiles: false
  ignore-missing-digests: false
  update-missing-digests: true
  lockfile-name: docker-lock.json

# To learn more about each flag, run `docker lock verify --help`
verify:
  env-file: .env
  lockfile-name: docker-lock.json
  ignore-missing-digests: false
  update-missing-digests: true
  exclude-tags: false

# To learn more about each flag, run `docker lock rewrite --help`
rewrite:
  exclude-tags: true
  lockfile-name: docker-lock.json
  tempdir: .
