trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

jobs:
- job: Test
  strategy:
    matrix:
      Windows:
        os.image: 'windows-latest'
      MacOS:
        os.image: 'macOS-latest'
      Ubuntu:
        os.image: 'ubuntu-latest'
  pool:
    vmImage: $(os.image)
  steps:
  - script: docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
    displayName: 'Login to Docker'
    env:
      DOCKER_USERNAME: $(DOCKER_USERNAME)
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
  - script: go test -race ./...
    displayName: 'Run all tests with race detector'
    condition: ne(variables['os.image'], 'windows-latest')
  - script: go test ./...
    displayName: 'Run all tests'
    condition: eq(variables['os.image'], 'windows-latest')

- job: Build
  dependsOn: Test
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: GOOS=linux GOARCH=amd64 go build -o docker-lock-linux
    displayName: 'Build linux'
  - script: GOOS=darwin GOARCH=amd64 go build -o docker-lock-mac
    displayName: 'Build mac'
  - script: GOOS=windows GOARCH=amd64 go build -o docker-lock-windows.exe
    displayName: 'Build windows'
  - publish: $(System.DefaultWorkingDirectory)/docker-lock-linux
    artifact: docker-lock-linux
  - publish: $(System.DefaultWorkingDirectory)/docker-lock-mac
    artifact: docker-lock-mac
  - publish: $(System.DefaultWorkingDirectory)/docker-lock-windows.exe
    artifact: docker-lock-windows

- job: Release
  dependsOn: Build
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - download: current
    artifact: docker-lock-linux
    displayName: Download docker-lock-linux
  - download: current
    artifact: docker-lock-mac
    displayName: Download docker-lock-mac
  - download: current
    artifact: docker-lock-windows
    displayName: Download docker-lock-windows
  - task: GithubRelease@0 
    displayName: 'Create GitHub Release'
    inputs:
      gitHubConnection: docker-lock-release
      repositoryName: michaelperel/docker-lock
      assets: |
        $(Pipeline.Workspace)/docker-lock-linux/docker-lock-linux
        $(Pipeline.Workspace)/docker-lock-mac/docker-lock-mac
        $(Pipeline.Workspace)/docker-lock-windows/docker-lock-windows.exe