name: cd-dockerhub

on:
  push:
    branches: [ 'miperel/gh-actions' ]

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # - name: install go
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: '1.15.0'

      # - name: build go binaries
      #   uses: goreleaser/goreleaser-action@v2
      #   with:
      #     args: build --snapshot

      # - name: setup qemu
      #   uses: docker/setup-qemu-action@v1

      # - name: setup docker buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: login to dockerhub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set tag
        run: echo "::set-output name=tag::notlatest"

      - name: check
        run: echo ${TAG}
        env:
          TAG: ${{ outputs.tag }}

      # - name: build and push
      #   run: |
      #     set -euo pipefail
      #     docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/386 -t safewaters/docker-lock:${TAG} .
      #   env:
      #     TAG: ${{ steps.vars.outputs.tag }}
