name: cd-master

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'

      - name: build go binaries
        uses: goreleaser/goreleaser-action@v2
        with:
          args: build --snapshot --rm-dist

      - name: setup qemu
        uses: docker/setup-qemu-action@v1

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to dockerhub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_SAFE_WATERS_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SAFE_WATERS_PASSWORD }}

      - name: build scratch images and push to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.scratch
          push: true
          tags: safewaters/docker-lock:latest
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64

      - name: build alpine images and push to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.alpine
          push: true
          tags: safewaters/docker-lock:alpine
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
