name: cd-tag

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'

      - name: build go binaries and release to github
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: setup qemu
        uses: docker/setup-qemu-action@v1

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to dockerhub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_SAFE_WATERS_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SAFE_WATERS_PASSWORD }}

      - name: set image tag
        run: |
          set -euo pipefail
          TAGV="${GITHUB_REF#refs/*/}"
          TAG="${TAGV/v}"
          echo "TAG=${TAG}" >> "${GITHUB_ENV}"
        shell: bash

      - name: build images and push to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: safewaters/docker-lock:${{ env.TAG }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
