name: CI

on:
  push:
    branches: [ 'miperel/gh-actions' ]
  pull_request:
    branches: [ master ]

jobs:
  dev-container:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: build dev container
        run: docker build -t devcontainer ./.devcontainer
        shell: bash

      - name: make
        run: docker run -v "${PWD}:/workspaces/docker-lock" devcontainer make lint install unittest
        shell: bash

      # - name: make inttest
      #   run: docker run -v "${PWD}:/workspaces/docker-lock" devcontainer make lint install unittest
      #   shell: bash
      #   if: github.event.pull_request.head.repo.full_name == github.repository

  all-hosts:
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
    runs-on: ${{ matrix.os }}
    env:
      DOCKER_VERSION: '19.03.9'

    steps:
      - uses: actions/checkout@v2

      - name: install mac prerequisites
        run: |
          set -euo pipefail
          curl -fsSL "https://github.com/docker/docker-credential-helpers/releases/download/v${OSXKEYCHAIN_VERSION}/docker-credential-osxkeychain-v${OSXKEYCHAIN_VERSION}-amd64.tar.gz" | gunzip | tar xopf -
          mv docker-credential-osxkeychain /usr/local/bin
          # docker cli does not come installed by default on the build agent
          curl -fsSL "https://download.docker.com/mac/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz" | gunzip | tar xopf -
          mv docker/docker /usr/local/bin
          mkdir -p "${HOME}/.docker"
          echo '{"credsStore":"osxkeychain"}' > "${HOME}/.docker/config.json"
        shell: bash
        env:
          OSXKEYCHAIN_VERSION: '0.6.3'
        if: matrix.os == 'macos-10.15'

      - name: install windows prerequisites
        run: |
          set -euo pipefail
          curl -fsSL "https://github.com/docker/docker-credential-helpers/releases/download/v${WINCRED_VERSION}/docker-credential-wincred-v${WINCRED_VERSION}-amd64.zip" -o docker-credential-wincred.zip
          unzip docker-credential-wincred.zip
          mkdir -p /usr/bin
          mv docker-credential-wincred.exe /usr/bin
          mkdir -p "${USERPROFILE}/.docker"
          echo '{"credsStore":"wincred"}' > "${USERPROFILE}/.docker/config.json"
          choco install -y mingw
        shell: bash
        env:
          WINCRED_VERSION: '0.6.3'
        if: matrix.os == 'windows-2019'

      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.0'

      - name: make install
        run: make install
        shell: bash

      - name: make unittest
        run: make unittest
        shell: bash

      # - name: make inttest
      #   run: make inttest
      #   shell: bash
      #   if: github.event.pull_request.head.repo.full_name == github.repository
