name: CI

on:
  push:
    branches: [ 'miperel/gh-actions' ]
  pull_request:
    branches: [ master ]

jobs:
  dev-container:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: 
        run: docker build -t devcontainer ./.devcontainer

      - name: Run a multi-line script
        run: docker run -v "${PWD}:/workspaces/docker-lock" devcontainer make lint install unittest
